---
title: "652-final"
author: "Janette Avelar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Library}
library(here)
library(tidyverse)
library(janitor)
```

```{r Data Import}
here::here("data")
enroll    <-  read_csv(here("data", "lang_enrolls_1958-2016.csv")) %>% 
              clean_names()
region    <-  read_csv(here("data", "lang_region.csv")) %>% 
              clean_names()
geo_code  <-  read_csv(here("data", "geo_codes.csv")) %>% 
              clean_names()
```

```{r Neat & Tidy}
# Need to covert geo_code into factor with 6 levels
# First fix those pesky NAs
geo_code[c(1:11), 1] = 1
geo_code[c(12:24), 1] = 2
geo_code[c(25:36), 1] = 3
geo_code[c(37:42), 1] = 4
geo_code[c(43:51), 1] = 5
geo_code[c(52:56), 1] = 6

# Now convert to factor
geo_code$geography_code <- factor(geo_code$geography_code,
                            levels = c(1:6))

# Add column for region name
geo_code <- geo_code %>% 
  mutate(region = factor(case_when(1 %in% geography_code ~ "Northeast",
                                   2 %in% geography_code ~ "Midwest",
                                   3 %in% geography_code ~ "Southeast",
                                   4 %in% geography_code ~ "Southwest",
                                   5 %in% geography_code ~ "Rocky Mountain",
                                   6 %in% geography_code ~ "Pacific",
                                   TRUE ~ as.character())))
# I don't know how to figure this out right now. Check back later.
```

